# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3382722a0f791db8926f5865e509bbfd025129a70c5434562d7142047958a363c5d420b5ffed3686ad8f67b085bc4b2bbbbfe0ea543318337c534877b9d0bf4

test:
  secret_key_base: 093676286444116bceefb3537e1a20b6192aabc85e0e910ff76b811e93adb1f8fd8b7f947049483e55bad49bed5649fd530d596d1b3801af1c8a1a0780db6754

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
